self_id = 3
listen_address = "127.0.0.1:7003"
data_dir = "/tmp/mesh-data-c"
bolt_address = "127.0.0.1:7689"
num_partitions = 4

[[peers]]
id = 1
address = "127.0.0.1:7001"

[[peers]]
id = 2
address = "127.0.0.1:7002"

[[peers]]
id = 3
address = "127.0.0.1:7003"
