#!/usr/bin/env bash
# Driver-matrix orchestrator. One invocation runs a single matrix
# cell: generate a server config from the axis flags, launch the
# server, wait for the Bolt port, run the per-language test suite
# against it, tear down on exit.
#
# Usage:
#   drivers/run-matrix.sh \
#     --lang=<py|js|go|java>    # which driver suite to run
#     [--auth=<none|basic>]     # default: none
#     [--tls=<off|on>]          # default: off
#     [--mode=<single>]         # default: single (routing comes in Phase 4)
#     [--bolt=<auto|4.4|5.0|5.4>]  # default: auto (full SUPPORTED set)
#
# Env overrides:
#   MESH_BIN     — path to the meshdb-server binary (default: target/release/meshdb-server)
#
# Exit code is the test runner's exit code. Server logs go to
# drivers/.run/logs/<timestamp>.log; on test failure the path is
# echoed to stderr.

set -euo pipefail

# Resolve the repo root from the script location so the script works
# regardless of the caller's cwd.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

LANG=""
AUTH="none"
TLS="off"
MODE="single"
BOLT="auto"

for arg in "$@"; do
  case "$arg" in
    --lang=*) LANG="${arg#*=}" ;;
    --auth=*) AUTH="${arg#*=}" ;;
    --tls=*)  TLS="${arg#*=}" ;;
    --mode=*) MODE="${arg#*=}" ;;
    --bolt=*) BOLT="${arg#*=}" ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

if [[ -z "$LANG" ]]; then
  echo "--lang is required (one of: py, js, go, java)" >&2
  exit 2
fi
case "$LANG" in py|js|go|java) ;; *) echo "unsupported --lang=$LANG" >&2; exit 2 ;; esac
case "$AUTH" in none|basic) ;; *) echo "--auth must be none|basic" >&2; exit 2 ;; esac
case "$TLS"  in off|on)     ;; *) echo "--tls must be off|on" >&2; exit 2 ;; esac
case "$MODE" in single)     ;; *) echo "mode=$MODE not supported yet (routing comes in Phase 4)" >&2; exit 2 ;; esac
case "$BOLT" in auto|4.4|5.0|5.4) ;; *) echo "--bolt must be auto|4.4|5.0|5.4" >&2; exit 2 ;; esac

MESH_BIN="${MESH_BIN:-target/release/meshdb-server}"
if [[ ! -x "$MESH_BIN" ]]; then
  echo "$MESH_BIN not found — run 'cargo build --release -p meshdb-server' first" >&2
  exit 2
fi

RUN_DIR="drivers/.run"
LOG_DIR="$RUN_DIR/logs"
CERTS_DIR="$RUN_DIR/certs"
DATA_DIR="$RUN_DIR/data"
CONFIG_FILE="$RUN_DIR/config.toml"
mkdir -p "$LOG_DIR"

# Wipe the data directory — every cell starts on a clean store so
# tests can assume an empty graph. Using a single `data/` path
# rather than per-axis variants keeps cleanup trivial.
rm -rf "$DATA_DIR"
mkdir -p "$DATA_DIR"

# Generate certs on demand if TLS is on. The script is idempotent so
# this is cheap to re-run across cells that all use the same cert.
if [[ "$TLS" == "on" ]]; then
  drivers/common/gen-cert.sh "$CERTS_DIR" >/dev/null
fi

# Generate the server config on the fly from the axis flags. The
# hand-written configs at the repo root (mesh.toml, cluster.toml)
# remain the canonical examples for operators; this one is a
# matrix-harness artifact regenerated every run.
{
  echo "# Generated by drivers/run-matrix.sh — do not edit."
  echo "# auth=$AUTH tls=$TLS mode=$MODE bolt=$BOLT"
  echo "self_id = 1"
  echo 'listen_address = "127.0.0.1:7401"'
  echo "data_dir = \"$DATA_DIR\""
  # Bind Bolt to `localhost` rather than `127.0.0.1`. The server
  # echoes this address back in its ROUTE reply, and some drivers
  # (neo4j-javascript-driver via Node's tls layer, JSSE) refuse
  # SNI on bare IP literals under TLS. `localhost` resolves to
  # 127.0.0.1 on every Linux + macOS runner we care about, so the
  # bind target is identical — only the advertised string differs.
  echo 'bolt_address = "localhost:7687"'
  if [[ "$BOLT" != "auto" ]]; then
    echo "bolt_advertised_versions = [\"$BOLT\"]"
  fi
  if [[ "$AUTH" == "basic" ]]; then
    echo ""
    echo "[[bolt_auth.users]]"
    echo 'username = "neo4j"'
    # Plain-text for the loopback harness; production uses bcrypt.
    echo 'password = "password"'
  fi
  if [[ "$TLS" == "on" ]]; then
    echo ""
    echo "[bolt_tls]"
    echo "cert_path = \"$CERTS_DIR/cert.pem\""
    echo "key_path = \"$CERTS_DIR/key.pem\""
  fi
} > "$CONFIG_FILE"

TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
LOG_FILE="$LOG_DIR/$TIMESTAMP-${LANG}-${AUTH}-${TLS}-${BOLT}.log"

# Launch the server. We background it and keep its pid so the trap
# can tear it down cleanly. RUST_LOG=info gives us enough detail to
# diagnose driver-side failures from the server's perspective.
echo "[run-matrix] launching $MESH_BIN --config $CONFIG_FILE (cell: lang=$LANG auth=$AUTH tls=$TLS bolt=$BOLT)" >&2
RUST_LOG="${RUST_LOG:-meshdb_server=info,meshdb_bolt=info,meshdb_rpc=warn}" \
  "$MESH_BIN" --config "$CONFIG_FILE" >"$LOG_FILE" 2>&1 &
SERVER_PID=$!

# shellcheck disable=SC2317
cleanup() {
  if kill -0 "$SERVER_PID" 2>/dev/null; then
    kill "$SERVER_PID" 2>/dev/null || true
    # Give the server a beat to flush its rocksdb file lock so a
    # subsequent run on the same data dir doesn't fail to open.
    wait "$SERVER_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

# Wait for the Bolt port to accept connections. 10s ceiling — well
# beyond what cold-start takes (~200ms on this hardware) but short
# enough that a stuck server doesn't block CI for minutes.
BOLT_HOST="127.0.0.1"
BOLT_PORT="7687"
for _ in $(seq 1 100); do
  if (echo > "/dev/tcp/${BOLT_HOST}/${BOLT_PORT}") 2>/dev/null; then
    break
  fi
  sleep 0.1
done
if ! (echo > "/dev/tcp/${BOLT_HOST}/${BOLT_PORT}") 2>/dev/null; then
  echo "[run-matrix] server never opened Bolt port ${BOLT_HOST}:${BOLT_PORT}" >&2
  echo "[run-matrix] server log: $LOG_FILE" >&2
  exit 1
fi

# Hand off to the per-language runner. Each runner reads connection
# info from env vars so the harness stays language-agnostic.
export MESH_BOLT_HOST="$BOLT_HOST"
export MESH_BOLT_PORT="$BOLT_PORT"
export MESH_BOLT_AUTH="$AUTH"
export MESH_BOLT_TLS="$TLS"
export MESH_BOLT_VERSION="$BOLT"

case "$LANG" in
  py)
    echo "[run-matrix] running drivers/python suite" >&2
    if ! (cd drivers/python && python -m pytest -q); then
      echo "[run-matrix] python suite failed" >&2
      echo "[run-matrix] server log: $LOG_FILE" >&2
      exit 1
    fi
    ;;
  js)
    echo "[run-matrix] running drivers/js suite" >&2
    if [[ ! -d drivers/js/node_modules ]]; then
      echo "[run-matrix] drivers/js/node_modules missing — run 'cd drivers/js && npm install' first" >&2
      exit 2
    fi
    if ! (cd drivers/js && npm test --silent); then
      echo "[run-matrix] js suite failed" >&2
      echo "[run-matrix] server log: $LOG_FILE" >&2
      exit 1
    fi
    ;;
  go)
    echo "[run-matrix] running drivers/go suite" >&2
    if ! (cd drivers/go && go test -count=1 ./...); then
      echo "[run-matrix] go suite failed" >&2
      echo "[run-matrix] server log: $LOG_FILE" >&2
      exit 1
    fi
    ;;
  java)
    echo "[run-matrix] running drivers/java suite" >&2
    # -q silences maven's banner / transfer chatter but keeps test
    # output; failing tests still surface individually.
    if ! (cd drivers/java && mvn -q test); then
      echo "[run-matrix] java suite failed" >&2
      echo "[run-matrix] server log: $LOG_FILE" >&2
      exit 1
    fi
    ;;
esac

echo "[run-matrix] cell passed: lang=$LANG auth=$AUTH tls=$TLS mode=$MODE bolt=$BOLT" >&2
