#!/usr/bin/env bash
# Driver-matrix orchestrator. One invocation runs a single matrix
# cell: generate server config(s) from the axis flags, launch the
# server(s), wait for the Bolt port(s), run the per-language test
# suite against peer A, tear down on exit.
#
# Usage:
#   drivers/run-matrix.sh \
#     --lang=<py|js|go|java>        # which driver suite to run
#     [--auth=<none|basic>]         # default: none
#     [--tls=<off|on>]              # default: off
#     [--mode=<single|routing>]     # default: single
#     [--bolt=<auto|4.4|5.0|5.4>]   # default: auto (full SUPPORTED set)
#
# In `--mode=routing` we spin up two Raft peers (peer A as seed,
# peer B as follower) with cross-linked `peers[].bolt_address` so
# the ROUTE table that drivers receive lists both. Drivers still
# connect to peer A; the `neo4j://` smoke test exercises the ROUTE
# path, the leader-aware WRITE role, and the follower-hop path.
#
# Env overrides:
#   MESH_BIN     — path to the meshdb-server binary (default: target/release/meshdb-server)
#
# Exit code is the test runner's exit code. Server logs go to
# drivers/.run/logs/<timestamp>.log; on test failure the path is
# echoed to stderr.

set -euo pipefail

# Resolve the repo root from the script location so the script works
# regardless of the caller's cwd.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

LANG=""
AUTH="none"
TLS="off"
MODE="single"
BOLT="auto"

for arg in "$@"; do
  case "$arg" in
    --lang=*) LANG="${arg#*=}" ;;
    --auth=*) AUTH="${arg#*=}" ;;
    --tls=*)  TLS="${arg#*=}" ;;
    --mode=*) MODE="${arg#*=}" ;;
    --bolt=*) BOLT="${arg#*=}" ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

if [[ -z "$LANG" ]]; then
  echo "--lang is required (one of: py, js, go, java)" >&2
  exit 2
fi
case "$LANG" in py|js|go|java) ;; *) echo "unsupported --lang=$LANG" >&2; exit 2 ;; esac
case "$AUTH" in none|basic) ;; *) echo "--auth must be none|basic" >&2; exit 2 ;; esac
case "$TLS"  in off|on)     ;; *) echo "--tls must be off|on" >&2; exit 2 ;; esac
case "$MODE" in single|routing) ;; *) echo "--mode must be single|routing" >&2; exit 2 ;; esac
case "$BOLT" in auto|4.4|5.0|5.4) ;; *) echo "--bolt must be auto|4.4|5.0|5.4" >&2; exit 2 ;; esac

MESH_BIN="${MESH_BIN:-target/release/meshdb-server}"
if [[ ! -x "$MESH_BIN" ]]; then
  echo "$MESH_BIN not found — run 'cargo build --release -p meshdb-server' first" >&2
  exit 2
fi

RUN_DIR="drivers/.run"
LOG_DIR="$RUN_DIR/logs"
CERTS_DIR="$RUN_DIR/certs"
mkdir -p "$LOG_DIR"

# Wipe the data directories — every cell starts on a clean store so
# tests can assume an empty graph.
rm -rf "$RUN_DIR/data-a" "$RUN_DIR/data-b"
mkdir -p "$RUN_DIR/data-a" "$RUN_DIR/data-b"

# Generate certs on demand if TLS is on. The script is idempotent so
# this is cheap to re-run across cells that all use the same cert.
if [[ "$TLS" == "on" ]]; then
  drivers/common/gen-cert.sh "$CERTS_DIR" >/dev/null
fi

# Port assignments. Peer A is what drivers connect to (and therefore
# what the `MESH_BOLT_HOST/PORT` env vars point at). Peer B exists only
# in routing mode so the ROUTE response has something non-trivial to
# return, and so follower-hop paths work in `neo4j://` sessions.
GRPC_PORT_A=7401
BOLT_PORT_A=7687
GRPC_PORT_B=7402
BOLT_PORT_B=7688

# Shared TOML body builders — kept DRY across single and routing
# modes. Every builder emits to stdout; callers redirect to the
# desired config file.
emit_bolt_sections() {
  if [[ "$BOLT" != "auto" ]]; then
    echo "bolt_advertised_versions = [\"$BOLT\"]"
  fi
  if [[ "$AUTH" == "basic" ]]; then
    echo ""
    echo "[[bolt_auth.users]]"
    echo 'username = "neo4j"'
    # Plain-text for the loopback harness; production uses bcrypt.
    echo 'password = "password"'
  fi
  if [[ "$TLS" == "on" ]]; then
    echo ""
    echo "[bolt_tls]"
    echo "cert_path = \"$CERTS_DIR/cert.pem\""
    echo "key_path = \"$CERTS_DIR/key.pem\""
  fi
}

# In routing mode we emit two configs so each peer can be launched
# with its own `meshdb-server --config`. The `peers` block on each
# cross-references the other with its Bolt endpoint so the ROUTE
# handler can list both siblings.
emit_routing_peers() {
  echo ""
  echo "[[peers]]"
  echo "id = 1"
  echo "address = \"127.0.0.1:$GRPC_PORT_A\""
  echo "bolt_address = \"localhost:$BOLT_PORT_A\""
  echo ""
  echo "[[peers]]"
  echo "id = 2"
  echo "address = \"127.0.0.1:$GRPC_PORT_B\""
  echo "bolt_address = \"localhost:$BOLT_PORT_B\""
}

CONFIG_A="$RUN_DIR/config-a.toml"
CONFIG_B="$RUN_DIR/config-b.toml"

# Build peer A's config (always). `localhost` as the Bolt bind gives
# us a DNS-safe advertised address for TLS SNI (Node's tls + JSSE
# both reject SNI on bare IP literals).
{
  echo "# Generated by drivers/run-matrix.sh — do not edit."
  echo "# cell: lang=$LANG auth=$AUTH tls=$TLS mode=$MODE bolt=$BOLT"
  echo "self_id = 1"
  echo "listen_address = \"127.0.0.1:$GRPC_PORT_A\""
  echo "data_dir = \"$RUN_DIR/data-a\""
  echo "bolt_address = \"localhost:$BOLT_PORT_A\""
  if [[ "$MODE" == "routing" ]]; then
    echo 'bootstrap = true'
    echo 'mode = "raft"'
  fi
  emit_bolt_sections
  if [[ "$MODE" == "routing" ]]; then
    emit_routing_peers
  fi
} > "$CONFIG_A"

if [[ "$MODE" == "routing" ]]; then
  {
    echo "# Generated by drivers/run-matrix.sh — do not edit."
    echo "# cell: lang=$LANG auth=$AUTH tls=$TLS mode=$MODE bolt=$BOLT (peer B)"
    echo "self_id = 2"
    echo "listen_address = \"127.0.0.1:$GRPC_PORT_B\""
    echo "data_dir = \"$RUN_DIR/data-b\""
    echo "bolt_address = \"localhost:$BOLT_PORT_B\""
    echo 'bootstrap = false'
    echo 'mode = "raft"'
    emit_bolt_sections
    emit_routing_peers
  } > "$CONFIG_B"
fi

TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
LOG_A="$LOG_DIR/$TIMESTAMP-${LANG}-${AUTH}-${TLS}-${BOLT}-${MODE}-a.log"
LOG_B="$LOG_DIR/$TIMESTAMP-${LANG}-${AUTH}-${TLS}-${BOLT}-${MODE}-b.log"

# Launch peer A. We background it and keep its pid so the trap can
# tear it down cleanly. RUST_LOG=info gives enough detail to
# diagnose driver-side failures from the server's perspective.
echo "[run-matrix] launching peer A: $MESH_BIN --config $CONFIG_A (cell: lang=$LANG auth=$AUTH tls=$TLS bolt=$BOLT mode=$MODE)" >&2
RUST_LOG="${RUST_LOG:-meshdb_server=info,meshdb_bolt=info,meshdb_rpc=warn}" \
  "$MESH_BIN" --config "$CONFIG_A" >"$LOG_A" 2>&1 &
SERVER_PID_A=$!
SERVER_PID_B=""

if [[ "$MODE" == "routing" ]]; then
  echo "[run-matrix] launching peer B: $MESH_BIN --config $CONFIG_B" >&2
  RUST_LOG="${RUST_LOG:-meshdb_server=info,meshdb_bolt=info,meshdb_rpc=warn}" \
    "$MESH_BIN" --config "$CONFIG_B" >"$LOG_B" 2>&1 &
  SERVER_PID_B=$!
fi

# shellcheck disable=SC2317
cleanup() {
  for pid in "$SERVER_PID_A" "$SERVER_PID_B"; do
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null || true
      wait "$pid" 2>/dev/null || true
    fi
  done
}
trap cleanup EXIT INT TERM

# Probe one or both Bolt ports before handing off to the test
# runner. 10s ceiling per port — cold-start takes ~200ms on this
# hardware, but CI runners are slower.
wait_for_port() {
  local port="$1"
  for _ in $(seq 1 100); do
    if (echo > "/dev/tcp/127.0.0.1/${port}") 2>/dev/null; then
      return 0
    fi
    sleep 0.1
  done
  return 1
}
if ! wait_for_port "$BOLT_PORT_A"; then
  echo "[run-matrix] peer A never opened Bolt port $BOLT_PORT_A" >&2
  echo "[run-matrix] server log: $LOG_A" >&2
  exit 1
fi
if [[ "$MODE" == "routing" ]] && ! wait_for_port "$BOLT_PORT_B"; then
  echo "[run-matrix] peer B never opened Bolt port $BOLT_PORT_B" >&2
  echo "[run-matrix] server log: $LOG_B" >&2
  exit 1
fi

# Hand off to the per-language runner. Each runner reads connection
# info from env vars so the harness stays language-agnostic. Drivers
# always point at peer A; in routing mode the ROUTE response tells
# them about peer B.
export MESH_BOLT_HOST="127.0.0.1"
export MESH_BOLT_PORT="$BOLT_PORT_A"
export MESH_BOLT_AUTH="$AUTH"
export MESH_BOLT_TLS="$TLS"
export MESH_BOLT_VERSION="$BOLT"
export MESH_BOLT_MODE="$MODE"

case "$LANG" in
  py)
    echo "[run-matrix] running drivers/python suite" >&2
    if ! (cd drivers/python && python -m pytest -q); then
      echo "[run-matrix] python suite failed" >&2
      echo "[run-matrix] server log: $LOG_A" >&2
      [[ -n "$SERVER_PID_B" ]] && echo "[run-matrix] peer B log: $LOG_B" >&2
      exit 1
    fi
    ;;
  js)
    echo "[run-matrix] running drivers/js suite" >&2
    if [[ ! -d drivers/js/node_modules ]]; then
      echo "[run-matrix] drivers/js/node_modules missing — run 'cd drivers/js && npm install' first" >&2
      exit 2
    fi
    if ! (cd drivers/js && npm test --silent); then
      echo "[run-matrix] js suite failed" >&2
      echo "[run-matrix] server log: $LOG_A" >&2
      [[ -n "$SERVER_PID_B" ]] && echo "[run-matrix] peer B log: $LOG_B" >&2
      exit 1
    fi
    ;;
  go)
    echo "[run-matrix] running drivers/go suite" >&2
    if ! (cd drivers/go && go test -count=1 ./...); then
      echo "[run-matrix] go suite failed" >&2
      echo "[run-matrix] server log: $LOG_A" >&2
      [[ -n "$SERVER_PID_B" ]] && echo "[run-matrix] peer B log: $LOG_B" >&2
      exit 1
    fi
    ;;
  java)
    echo "[run-matrix] running drivers/java suite" >&2
    # -q silences maven's banner / transfer chatter but keeps test
    # output; failing tests still surface individually.
    if ! (cd drivers/java && mvn -q test); then
      echo "[run-matrix] java suite failed" >&2
      echo "[run-matrix] server log: $LOG_A" >&2
      [[ -n "$SERVER_PID_B" ]] && echo "[run-matrix] peer B log: $LOG_B" >&2
      exit 1
    fi
    ;;
esac

echo "[run-matrix] cell passed: lang=$LANG auth=$AUTH tls=$TLS mode=$MODE bolt=$BOLT" >&2
